name: Resizable
author: Ryan Florence
category: Effects
tags: [spinner, animation, games]
docs: http://moodocs.net/rpflo/mootools-rpflo/SpriteAnimation
docs: http://moodocs.net/rpflo/mootools-rpflo/SpriteAnimation
current: 1.0